### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by takanuva15** [Dummiesman/BNDImportExport#3]
Hi, I tried to import a .bnd file in Blender 2.93 using this addon but it gives me the error:

`AttributeError: module 'time' has no attribute 'clock' in Python 3.8`

I looked online and it seems that the `time.clock()` function doesn't exist anymore in Python 3.8+. Can you please update the addon so it works in Blender 2.93?

(Here's a [reference link](https://stackoverflow.com/a/58569410) that shows some possible fixes.)

**Comment by takanuva15** [comment]
(Please also update the latest zip release with the patch. Thanks!)
